[project]
name = "projeto-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
]
