# This is a basic workflow to help you get started with Actions
name: ML CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "dev" branch
  push:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run 
# sequentially or in parallel
jobs:
  # This workflow will contain two jobs, CI and CD.
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version-file: "pyproject.toml"

      - name: Run model training unit tests
        run: |
            uv run pytest unit_test_train_model.py

  CD:
        needs: CI

        runs-on: ubuntu-latest

        steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, 
        # so your job can access it
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            cache-dependency-glob: "uv.lock"

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
                python-version-file: "pyproject.toml"

        - name: Train model
          run: |
            uv run train_model.py

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ml-model
            path: model.pkl
            retention-days: 90

        - name: Agendar
          run: echo "Você pode fazer o upload de uma DAG do Airflow em uma pasta específica"

        - name: Run deploy tests
          run: echo "Aqui vc executa um teste para checar os artefatos"
          

        

